# Generated by Django 3.2.7 on 2021-09-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='images',
            field=models.JSONField(default=[]),
        ),
    ]
