# Generated by Django 3.2.7 on 2021-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='all_in_one',
            field=models.JSONField(),
        ),
    ]
