# Generated by Django 3.2.7 on 2021-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyq', '0002_surveyresponse_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='images',
            field=models.JSONField(default={}),
        ),
    ]
