# Generated by Django 3.2.7 on 2021-09-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyq', '0003_alter_surveyresponse_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='images',
        ),
    ]
