# Generated by Django 3.2.7 on 2021-09-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Reg_User',
        ),
    ]
